Avoid using ssh-keyscan and avoid stricthostkeychecking

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -238,23 +238,27 @@ jobs:
 
       - name: Setup ssh
         env:
-          SSH_KEY: ${{ vars.SSH_PRIVATE_KEY }}
-          SSH_HOST: ${{ vars.SSH_PRODUCTION_URL }}
+          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+          SSH_HOST: ${{ secrets.SSH_PRODUCTION_URL }}
         run: |
           mkdir -p ~/.ssh
 
-          echo "$SSH_KEY" >> ~/.ssh/github_actions
+          echo "$SSH_KEY" > ~/.ssh/github_actions
           chmod 600 ~/.ssh/github_actions
 
           # Tambahkan host ke known_hosts (bypass host verification)
-          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts 2>/dev/null
+          # ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts 2>/dev/null || echo "ssh-keyscan failed, will skip host verification"
 
       - name: Tes ssh to the server
         env:
-          SSH_HOST: ${{ vars.SSH_PRODUCTION_URL }}
-          SSH_USER: ${{ vars.SSH_PRODUCTION_USER }}
+          SSH_HOST: ${{ secrets.SSH_PRODUCTION_URL }}
+          SSH_USER: ${{ secrets.SSH_PRODUCTION_USER }}
         run: |
-          ssh -i ~/.ssh/github_actions -o ProxyCommand="cloudflared access ssh --hostname $SSH_HOST" $SSH_USER@$SSH_HOST "echo 'Hello from GitHub Actions!'"
+          ssh -i ~/.ssh/github_actions \
+              -o StrictHostKeyChecking=no \
+              -o UserKnownHostsFile=/dev/null \
+              -o ProxyCommand="cloudflared access ssh --hostname $SSH_HOST" \
+              "$SSH_USER@$SSH_HOST" "echo 'Hello from GitHub Actions!'"
 
       # Blue-Green Deployment
       # - name: Deploy to Production
